thephpleague/html-to-markdown

HTML_To_Markdown.php

When "strip_tags" option is on, divs vanish. However, they often need a line feed.
I chose to add a paragraph break, but a line break would be just as ok for me.
Thanks for the great code!

Generalizing to convert any HTML (incl. email!) to markdown

---

CHANGELOG.md
HTML_To_Markdown.php
tests/HTML_To_MarkdownTest.php

Fixed #31
All feedback is welcome. Thanks.

<a> tags with identical href and inner text are now rendered using angular bracket syntax

---

HTML_To_Markdown.php
tests/HTML_To_MarkdownTest.php

Prevents extra spaces between back to back div's.
Previously, with `strip_tags` `true`, the HTML:
```
<div>Hello</div>
<div>World</div>
```
Would render to:
```
Hello
World
```
Notice the extra space in front of "World". This fixes the extra space.

Treat <div> as a block level element.

---

src/HtmlConverter.php
tests/HtmlConverterTest.php

Empty HTML strings should result in empty Markdown documents

---

CHANGELOG.md
src/HtmlConverter.php
tests/HtmlConverterTest.php

In CommonMark, both the single * and _ characters indicate emphasis. However,
the rules for parsing those characters are slightly different. This is
especially noticeable when combining empahsis and strong emphasis using the
* and ** indicators in the same run of test (as issue #58 demonstrated).
This change produces the resulting Markdown you'd expect to see in such cases.

Change default italic character to `_` (#58)

---

src/Converter/ParagraphConverter.php

When you pass the paragraphs `<p>0</p>` or `<p></p>` to the convert function
of the ParagraphConverter, the return value will be an empty string, because
the statement `$element->getValue()` is considered to be false. 
I added another check to that statement, so that in the case of an value of 0 in the paragraph,
the whole statement is considered to be true and 0 is returned. So now an input of `<p>0</p>` is converted to 0.

Fixes conversion of <p>0</p> paragraphs (Issue #66)

---

src/Converter/EmphasisConverter.php
tests/HtmlConverterTest.php

This is quite common in html
```This is <strong>bold </strong>text```
ie. the space being within the strong tags
Previously html-to-markdown would convert that to
```This is **bold **text```
Which is invalid. This PR moves the space outside the markdown tags, eg.
```This is **bold** text```

Fix for preceeding or trailing spaces within emphasis tags

---

src/HtmlConverter.php
tests/HtmlConverterTest.php

Adding HtmlConverter::__invoke as an alias to HtmlConverter::convert
to enable calling HtmlConverter object as functions

Enabling calling HtmlConvert as a function

---

tests/HtmlConverterTest.php

Reported as issue #80, seems to be working. Perhaps fixed elsewhere and not noted, but adding a test to prove the functionality.

Add test for a self closing br tag as reported in #80

---

src/Converter/EmphasisConverter.php

A tag just containing spaces (or non-breaking spaces) would end up as ** or **** which would produce incorrect rendering.
The following is nonsensical, but often produced by WYSIWYG HTML editors:
`<b>&nbsp;</b>`
This fix prevents this being produced:
`****`
Or a runaway ** bold tag.

Fix edge case for tags containing only whitespace.

---

src/HtmlConverter.php

This PR will fix issue #63 
Please notice that the code example in the issue is malformed. The head and body tags on it aren't escaped and all tags inside code tags must be escaped.
Using this snippet returns the correct markdown:
`<pre><code>...
&lt;script type = "text/javascript"&gt;
function startTimer() {
var tim = window.setTimeout("hideMessage()", 5000)
}
&lt;/head&gt;
&lt;body&gt;
...</code></pre>`

Fix sanitization bug (#63)

---

src/Converter/ParagraphConverter.php
tests/HtmlConverterTest.php

Hi!
This solves issue #77. Blockquote-like paragraphs are escaped with a \. I also added the corresponding tests.
Input:
`<p>&gt; &gt; Look at me! &lt; &lt;</p>`
Actual:
`\> > Look at me! < <`
Expected:
`\> > Look at me! < <`

Escape blockquote-like paragraphs (#77)

---

.travis.yml

And don't allow failures on 7.0 since it went gold

[Travis] Test on PHP 7.1

---

src/Converter/ParagraphConverter.php
tests/HtmlConverterTest.php

This fixes issue #76 and sets the path for future sanitization tasks.
On the ParagraphConverter I added a new function that will handle all the sanitization needed. Right now it has two different sanitizators, one for headerlike characters and one for blockquotelike characters.
Since it scans the paragraph contents line by line, new sanitizators can be added in the future.
I also added new tests.
Please check it out and tell me what you think.

Sanitization function for ParagraphConverter

---

src/Converter/ParagraphConverter.php
src/Element.php
tests/HtmlConverterTest.php

Hi!
This fixes issue #73. It will match ordered list like characters via regex and will add a \ to escape them.

Escaping ordered list-like lines

---

src/Converter/ParagraphConverter.php
tests/HtmlConverterTest.php

Hi!,
I just rewrote the sanitization function to be able to parse different characters on a single call instead of having to add a new function with each new character to sanitize.
Right now it has three functions:
- escapeFirstCharacters: Will escape problematic characters that appear at the beginning of the line, like `>` or `~~~`
- escapeOtherCharacters: Will escape other type of characters that can appear anywhere on the string, like ``
- escapeOtherCharactersRegex: Will escape other type of characters via regex. List-like constructions, for example `123)`
I think it's a better approach than the previous one and sets the path for future escaping necessities. What do you think?
This will solve #67, #65 and #64

Simple refactor for the sanitization function

---

tests/HtmlConverterTest.php

Fixes #113. Please see that issue for more details. Technically, `img` is a [void element](http://w3c.github.io/html-reference/syntax.html#void-element) as well, but that's a special case in Markdown. I haven't looked into image handling too deeply yet, but someone finds a breaking test for spacing inside `img` elements in the immediate future, it might be a good idea to incorporate it into this PR.

Added tests for spaces in void elements (#113)

---

README.md
src/Converter/HardBreakConverter.php
src/HtmlConverter.php
tests/HtmlConverterTest.php

Fixes #112. Please see that issue for more details. Adds `hard_break` config option. By default, it is set to `false`, which will cause `br` tags to be converted to two spaces followed by a newline character, preserving current behavior. When `hard_break` is set to `true`, those two spaces will be omitted, as per GitHub Flavored Markdown. `README.md` has been updated, new tests added, and everything seems to be in order.

Added hard_break option for GFM line breaks (#112)

---

src/Converter/TextConverter.php
tests/HtmlConverterTest.php

Fixes #116. Please see that issue for more information. Added three new tests. Linted related code a bit in `TextConverter.php` for clarity and ease of future changes. All tests succeed. Related to #14.
This is a bit brute-force, I'll admit. I hope this can be incorporated as-is until further fail cases can be added in the form of tests. Everything seems to be in order for the time being.

Fix phantom space when newline follows br (#116)

---

src/Converter/LinkConverter.php

This solves issue #119.
It's just a `trim()` function over the link text.

Trim the link text to avoid incorrect syntax

---

README.md
src/Environment.php
src/HtmlConverter.php
tests/EnvironmentTest.php
tests/HtmlConverterTest.php

I need to customize rules, because I'm using modified Markdown, with couple of custom rules. I decided to prepare a logic for inject Environment object to HtmlConverter, so I am now able to change converters. Also it is easier to refactor tests to make them unit, because now test cases runs all the logic from library.
I tried not to break BC, but I would appreciate your review, if I didn't miss some important cases.

Allow to inject Environment object

---

src/HtmlConverter.php

Fix: Add missing throws annotation

---

src/Element.php
src/HtmlConverter.php

Fix: Update docblocks

---

src/Converter/TextConverter.php
tests/HtmlConverterTest.php

Escapes the characters '[' and ']' on text elements so that
```
<p>test[test]</p>
```
gets converted to
```
test\[test\]
```

Escape square brackets

---

src/Converter/EmphasisConverter.php
tests/HtmlConverterTest.php

`'Emphasis with no<em> </em>text<strong> preserves</strong> spaces.'`
The result is this:
`'Emphasis with notext **preserves** spaces.'`
I think the text should be this: 
`'Emphasis with no text **preserves** spaces.'`

Preserve spaces that are emphasized

---

src/HtmlConverter.php

I have created a new function that allows an easier way of static calling.
I am using Laravel and decided to use the Facade feature as so:
use Facades\League\HTMLToMarkdown\HtmlConverter as Markup;
$converted = Markup::setOptions(['strip_tags' => true])->convert('<span>Turnips!</span>');
The `setOptions` function made it possible to call the library in one line.

Created setOptions function for chainable calling

---

src/Converter/CodeConverter.php
tests/HtmlConverterTest.php

A paragraph that follows code will not be output on a new line. This new test exposes the issues.
#147

Add newlines after code block

---

src/Converter/CodeConverter.php
src/Converter/PreformattedConverter.php
tests/HtmlConverterTest.php

Fixes #26
Fixes #70
Undoes most incompatible behavior of #102
Fixes #140
Fixes #161
Blocks https://github.com/friendica/friendica/pull/5765#issuecomment-422097903
Per the CommonMark spec, single backtick (inline) code blocks produce `<p><code>....</code></p>` tags without honoring new lines, while multiple backtick (block) code blocks produce `<pre><code>...</code></pre>` tags, keeping new lines.
Going the other way, we should only convert to a multiple-backticks code block if the `<code>` tag is inside a `<pre>` tag. By himself, a HTML `<code>` tag is inline and doesn't show new lines, only the `<pre>` tag confers this ability.
This PR also removes references to `PHP_EOL` where `\n` was mostly used.
Tests have been updated.

<code> tags are blocks if inside <pre>, inline otherwise

---

src/Converter/DefaultConverter.php

This PR includes a fix for #165.
I'm not sure if there are other cases that would rely on a similar handling, but I'm dealing with the paragraph after table situation. Since this is a unique case, I don't think we need to move the `$element->getTagName() === 'table'` condition to a separate method. I'm open to refactoring that if it's necessary.

Fix #165: Paragraph after table.

---

src/Element.php
tests/HtmlConverterTest.php

This PR removes the `code` element from the array returned by `isBlock` function because `<code>` is an inline HTML element, not a block.
Fixes #174

Removed `code` from the block elements list since it's inline

---

README.md
src/Converter/CommentConverter.php
src/HtmlConverter.php
tests/HtmlConverterTest.php

This PR adds a new option to preserve comments. The current behavior is the default, i.e. strip all comments off.
As suggested by @Rarst on #177 the available options for `preserve_comments` are:
* `false` preserve no comment (**default**)
* `true` preserve all comments
* `string[]` preserve specific comments, e.g. `array( 'more' )`.
The option may be passed to the converter constructor, this way:
```
$markdown = new HtmlConverter(array(
'preserve_comments' => true,
));
```

Added option to preserve comments

---

src/Converter/TextConverter.php
tests/HtmlConverterTest.php

This changes is needed to preserve HTML entities present in the input.
```html
<p>&lt;hr&gt;</p>
```
A literal `<hr>` tag rendered as text.
```markdown
<hr>
```
This displays a horizontal bar when converted back to HTML with any Markdown parser.
```markdown
&lt;hr&gt;
```
Once parsed, it is correctly displayed as the literal characters `<hr>` in a paragraph.
Related issue in Friendica, our project that uses HTML to Markdown: https://github.com/friendica/friendica/issues/7808

Escape HTML entities in TextConverter::convert

---

README.md
src/Converter/LinkConverter.php
src/HtmlConverter.php
tests/HtmlConverterTest.php

Feature request thephpleague/html-to-markdown#187
* Configuration `use_autolinks` added
* When set to `false`, the short link syntax `<url>` will not be used

Make autolinking configurable

---

README.md
src/Converter/ConverterInterface.php
src/Converter/DefaultConverter.php
src/Converter/TableConverter.php
src/HtmlConverter.php
tests/HtmlConverterTest.php

This adds support for Markdown tables and resolves issue #201. 
Because tables are extended Markdown the converter is not enabled by default and needs to be added by the user explicitly.
Implementing more complex conversions like tables is not easy to do in purely bottom-up fashion. To make this easier this PR also adds a `PreConverterInterface` which converters can implement to be called before children are traversed. This provides and opportunity to inspect and modify the DOM while children are still unmodified.

Add support for tables

---

src/Converter/EmphasisConverter.php
src/Element.php
src/ElementInterface.php
tests/HtmlConverterTest.php

This is a fix for issue #199.
By checking the type of the immediate previous or following sibling node we can avoid emitting the incorrect style. To access the previous sibling we need to cache it on Element creation because it will already be replaced by markdown when the current node is being converted.

Fix consecutive emphasis producing incorrect markdown

---

README.md
src/Converter/LinkConverter.php
src/HtmlConverter.php
tests/HtmlConverterTest.php

I wanted to remove `a` tags that don't have `href` but retain the other `a` tags.
To retain the default behavior, I added `strip_placeholder_links` which defaults to `false`.

Added stripping of placeholder links

---

src/Converter/ListItemConverter.php
tests/HtmlConverterTest.php

This PR updates this library to use four spaces for list indentation instead of two spaces. The primary motivation for this is to make this markdown compatible with commonmark — which expects four spaces.
```markdown
- red
- green
- turquoise
- teal
- forest
- blue
- red
- green
- turquoise
- teal
- forest
- blue
```

Convert lists from two space indentation to four space indentation

---

src/HtmlConverter.php
tests/HtmlConverterTest.php

This is a fix for https://github.com/thephpleague/html-to-markdown/issues/212: if you pass HTML that begins with a comment (like `<p>hi</p>`) to `HtmlConverter->convert`, the resulting markdown looks like this: `<html><body>hi\n`.
This is because `DOMDocument->loadHTML` actually puts that first comment at the root of the document, *outside* the `html` and `body` tags. The `sanitize` method only removes `html` and `body` tags [if they're at position 0 of the markdown string](https://github.com/bigsweater/html-to-markdown/blob/03fad17ef570ae3af62bdebb7a31e59fda7226d7/src/HtmlConverter.php#L230-L232) -- but with the comment at the root of the document, the position of the tags will always be > 0, so they never get removed (and that first comment is never removed, either).
So this adds a step …

#212: Find and move any misplaced comment nodes

---

CHANGELOG.md
composer.json
src/Converter/LinkConverter.php
src/Converter/ListItemConverter.php
src/Converter/TableConverter.php
src/Element.php
src/HtmlConverter.php

Allow newer versions of phpstan and fixed `mixed`-related issues the new version detects.

Upgrade phpstan
